name: pull-request

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build
      run: |
        npm i
        npm run build
  Test:
    needs: [Build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
        cache: 'npm'

    - name: Test
      run: |
        npm i
        npm test

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        # token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: ./coverage/clover.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
  Quality:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
        cache: 'npm'

    - name: Test
      run: |
        npm i
        npm test

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.9.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  Docs:
    needs: [Quality]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
        cache: 'npm'

    - name: Build docs
      run: |
        npm i && npm run docs
